#!/bin/bash

source $1

while read -r line; do
    case $line in
    WS*)
        ws="  ${line:2}  %{F-}"
        ;;
    NOC*)
        noc="%{F$c2} ${line:3}%{F-}"
        ;;
    BAT*)
        bat="%{F$afg}%{B$aabg}  ${line:3}  %{F-B-}"
        ;;
    DAT*)
        dat="%{F$afg}%{B$abg}  ${line:3}  %{F-B-}"
        ;;
    esac

    lpad="%{B$abg} %{B-}"

    echo -e "%{l}$lpad$ws$noc%{r}$bat$dat"
done
