#!/bin/bash

# dependencies: xprop xdotool

# main loop
xprop -spy -root _NET_CLIENT_LIST | while read -r line; do
    id_list=(`echo $line`)

    for id in ${id_list[@]:4}; do
        name=$(xdotool getwindowname $id)
        buff+="${name:0:20} "
    done

    echo $buff
    buff=""
done




